git@github.com:inahuelzapata/SaleJuntada.gitopt_in_rules:
  - explicit_init
  - first_where
  - conditional_returns_on_newline
  - redundant_nil_coalescing
  - switch_case_on_newline
  - closure_spacing
  - sorted_imports
  - attributes
  - yoda_condition
  - literal_expression_end_indentation
  - unneeded_parentheses_in_closure_argument
  - private_over_fileprivate
  - redundant_optional_initialization
  - redundant_type_annotation
  - toggle_bool
  - file_types_order
  - untyped_error_in_catch
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - private_outlet
  - unused_imports

excluded:
  - Pods

identifier_name:
  min_length: 1
  max_length: 50

type_name:
  min_length: 1
  max_length: 50
